name: usm
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.19.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_storage: ^11.0.16
  image_picker: ^0.8.6
  firebase_ui_database: ^1.3.11
  firebase_database: ^10.0.16
  firebase_core: ^2.8.0
  controller: ^0.1.12
  material_segmented_control: ^3.1.2
  rich_text_editor_controller: ^0.0.4
  rich_text_controller: ^1.4.2
  flexible_text_editing_controller: ^1.0.0
  material: ^1.0.0
  file_picker: ^4.6.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.2
  build_runner: ^2.3.3

flutter:
  uses-material-design: true
  assets:
  - images/
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
