
// File generated by FlutLab.
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for iOS - '
          'try to add using FlutLab Firebase Configuration',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'it not supported by FlutLab yet, but you can add it manually',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'it not supported by FlutLab yet, but you can add it manually',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'it not supported by FlutLab yet, but you can add it manually',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBniH4XVI7nh4YQjzfBp6C1tGaIF_uJt74',
    authDomain: 'sistem-informasi-mahasis-68853.firebaseapp.com',
    databaseURL: 'https://sistem-informasi-mahasis-68853-default-rtdb.europe-west1.firebasedatabase.app',
    projectId: 'sistem-informasi-mahasis-68853',
    storageBucket: 'sistem-informasi-mahasis-68853.appspot.com',
    messagingSenderId: '798109529676',
    appId: '1:798109529676:web:830dcf1f95f2cd3190e6e9'
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAkMIG_8l5etu2miNGntv-E7z1_0og0vGQ',
    appId: '1:798109529676:android:6a792ef11960f7e490e6e9',
    messagingSenderId: '798109529676',
    projectId: 'sistem-informasi-mahasis-68853',
    storageBucket: 'sistem-informasi-mahasis-68853.appspot.com'
  );
}
